#' A Class which represents a guild object
#' @export
#'
#' @slot id
#' @slot name
#' @slot icon
#' @slot splash
#' @slot owner
#' @slot owner_id
#' @slot permissions
#' @slot region
#' @slot afk_channel_id
#' @slot afk_timeout
#' @slot embed_enabled
#' @slot embed_channel_id
#' @slot verification_level
#' @slot default_message_notifications
#' @slot explicit_content_filter
#' @slot roles
#' @slot emojis
#' @slot features
#' @slot mfa_level
#' @slot application_id
#' @slot widget_enabled
#' @slot widget_channel_id
#' @slot system_channel_id
#' @slot joined_at
#' @slot large
#' @slot unavailable
#' @slot member_count
#' @slot voice_stated
#' @slot members
#' @slot channels
#' @slot presences
#' @slot max_presences
#' @slot max_members
#' @slot vanity_url_code
#' @slot description
#' @slot premium_tier
#' @slot premium_subscription_count

Guild <- R6Class("Class",
  public = list(
    initialize <- function(data) {
      self$id = data$id
      self$name = data$name
      self$icon = data$icon
      self$splash = data$splash
      self$owner = data$owner
      self$owner_id = data$owner_id
      self$permissions = data$permissions
      self$region = data$region
      self$afk_channel_id = data$afk_channel_id
      self$afk_timeout = data$afk_timeout
      self$embed_enabled = data$embed_enabled
      self$embed_channel_id = data$embed_channel_id
      self$verification_level = data$verification_level
      self$default_message_notifications = data$default_message_notifications
      self$explicit_content_filter = data$explicit_content_filter
      self$roles = data$roles
      self$emojis = data$emojis
      self$features = data$features
      self$mfa_level = data$mfa_level
      self$application_id = data$application_id
      self$widget_enabled = data$widget_enabled
      self$widget_channel_id = data$widget_channel_id
      self$system_channel_id = data$system_channel_id
      self$jonied_at = data$jonied_at
      self$large = data$large
      self$unavailable = data$unavailable
      self$member_count = data$member_count
      self$voice_states = data$voice_states
      self$members = data$members
      self$channels = data$channels
      self$presences = data$presences
      self$max_presences = data$max_presences
      self$max_members = data$max_members
      self$vanity_url_code = data$vanity_url_code
      self$description = data$description
      self$banner = data$banner
      self$premium_tier = data$premium_tier
      self$premium_subscription_count = data$premium_subscription_count
    }
    id = NA,
    name = NA,
    icon = NA,
    splash = NA,
    owner = NA,
    owner_id = NA,
    permissions = NA,
    region = NA,
    afk_channel_id = NA,
    afk_timeout = NA,
    embed_enabled = NA,
    embed_channel_id = NA,
    verification_level = NA,
    default_message_notifications = NA,
    explicit_content_filter = NA,
    roles = NA,
    emojis = NA,
    features = NA,
    mfa_level = NA,
    application_id = NA,
    widget_enabled = NA,
    widget_channel_id = NA,
    system_channel_id = NA,
    joined_at = NA,
    large = NA,
    unavailable = NA,
    member_count = NA,
    voice_states = NA,
    members = NA,
    channels = NA,
    presences = NA,
    max_presences = NA,
    max_members = NA,
    vanity_url_code = NA,
    description = NA,
    banner = NA,
    premium_tier = NA,
    premium_subscription_count = NA
  )

)
